# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'Updated fork without posts of a brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>, forked by @KonradHoeffner.'
url:              https://hyde.getpoole.com
baseurl:          ''

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
#plugins:

# Custom vars
version:          3.0.0
